#!/usr/bin/env bash
# Usage: 1p [-j|-p|-c|-b] [ACCOUNT...]

export op1p_session_dir="$HOME/.op/.sessions"
mkdir -p "$op1p_session_dir"
chmod 700 "$op1p_session_dir"

have_session() {
  [[ ":$(env | fex '=1 /^OP_SESSION_/_-1' | tr -s ' \n' ':'):" = *":${1}:"* ]]
}
export -f have_session

auth_type=human
case "$1" in
-b) # Basic authentication
  auth_type=basic;;
-p) # Print password
  auth_type=password;;
-c) # Print name:password
  auth_type=userpass;;
-j) # Print item JSON
  auth_type=json;;
esac

if [[ "$auth_type" != human ]]; then
  shift
fi

session_refresh() {
  local name="$1"
  local max_age="${2:-1500}"
  local f="$op1p_session_dir/$1"
  if [[ -f "$f" ]]; then
    . "$f"
    if have_session "$name" && [[ $(($(date +%s) - $(date -r "$f" +%s))) -le $max_age ]]; then
      return 0
    fi
  fi
  text="$(op signin "$name")"
  if [[ -z "$text" ]]; then
    rm -f "$f"
    return 1
  fi
  eval "$(echo "$text" | tee "$f")"
  chmod 600 "$f"
  return 0
}
export -f session_refresh

if [[ -n "$1" ]]; then
  session=("$1")
  shift
else
  session=($(jq -r '.accounts[].shorthand' "$HOME/.op/config"))
fi

# Refresh sessions
for sn in "${session[@]}"; do
  if ! session_refresh "$sn"; then
    echo "Session unavailable: $sn" 1>&2
  else
    . "$op1p_session_dir/$sn"
  fi
done

sel="$(
  for sn in "${session[@]}"; do
    op list items --account="$sn" |
      jq --arg sn "$sn" -r '.[] | "\($sn)\t\(.uuid)\t\(.overview.title)"'
  done |
  fzf --preview="op get item --account={1} {3} | jq 'del(.details)'" -d $'\t'
)"

if [[ -z "$sel" ]]; then
  exit 0
fi

sn="$(printf '%s' "$sel" | fex $'\t1')"
uuid="$(printf '%s' "$sel" | fex $'\t2')"
json="$(op get item --account="$sn" "$uuid")"
query() {
  printf '%s' "$json" | jq "$@"
}

printf $'\r'

case $auth_type in
human)
  # Username
  query -r '.details.fields[] | select(.type == "T" and .designation == "username").value'
  # Password
  query -r '.details.fields[] | select(.type == "P" and .designation == "password").value' | pbcopy
  # TOTP
  if [[ -n "$(command -v gen-totp)" ]]; then
    totpuri="$(query -r '[.details.sections[].fields[]] | map(select(.v | startswith("otpauth://"))) | first.v')"
    if [[ -n "$totpuri" ]]; then
      echo "OTP: $(gen-totp "$totpuri")"
    fi
  fi
  ;;

userpass)
  query -r '.details.fields |
    (.[] | select(.type == "T" and .designation == "username").value) as $user |
    (.[] | select(.type == "P" and .designation == "password").value) as $pass |
    [$user, $pass] | map(select(. != "")) | join(":")'
  ;;

password)
  query -r '.details.fields[] | select(.type == "P" and .designation == "password").value'
  ;;

basic)
  query -r '.details.fields |
    (.[] | select(.type == "T" and .designation == "username").value) as $user |
    (.[] | select(.type == "P" and .designation == "password").value) as $pass |
    [$user, $pass] | map(select(. != "")) | join(":") | @base64'
  ;;

json)
  query .
  ;;
esac